{
    "name": "BS Create Form Quotation G Plus",
    "version": "17.0.0.2",
    "author": "Basic-Solution Co., Ltd.",
    "maintainer": "varit",
    "website": "https://www.basic-solution.com/",
    "category": "Sales",
    "depends": [
        "sale",
        "sale_order_note_template",
        "bs_sale_order_hrp",
        "partner_contact_person",
        "l10n_th_partner",
        "salesperson_signature",
        "hr",
    ],
    "data": [
        "report/components/report_footer.xml",
        "report/components/report_header.xml",
        "report/components/report_main_content.xml",
        "report/report_g_plus.xml",
        "report/request_report.xml",
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
