{
    "name": "BS Create Tax Invoice Herring Puls And Service Preprint",
    "version": "17.0.0.4",
    "author": "Basic-Solution Co., Ltd.",
    "maintainer": "varit",
    "website": "https://www.basic-solution.com/",
    "category": "account",
    "depends": [
        "account",
        "l10n_th_account_tax",
        "l10n_th_partner",
        "bs_contact_add_field",
        "l10n_th_amount_to_text",
    ],
    "data": [
        "report/components/report_footer.xml",
        "report/components/report_header.xml",
        "report/components/report_main_content.xml",
        "report/report_herring_puls_and_service_preprint.xml",
        "report/request_report.xml",
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
