{
    'name': 'BS Create Report Billing HRP',
    'version': '17.0.0.3',
    'author': 'Basic-Solution Co., Ltd.',
    'website': 'https://www.basic-solution.com/',
    "category": "Accounting",
    "depends": ["account", "account_billing", "bs_show_signature", "bs_company_address_ext"],
    'data': [
        'report/components/report_template_company_info.xml',
        'report/components/report_header_partner_info.xml',
        'report/components/report_main_content.xml',
        'report/components/report_footer.xml',
        'report/bs_create_report_billing_hrp_template.xml',
        'report/report_bs_create_report_billing_hrp_page.xml',
        'report/request_report.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
