{
    'name': 'BS Create Form Receipt TH HRP',
    'version': '17.0.0.1',
    'author': 'Basic-Solution Co., Ltd.',
    'website': 'https://www.basic-solution.com/',
    "license": "AGPL-3",
    "category": "Accounting",
    "depends": ["account","account_asset_management","bs_pdc","bs_show_signature"],
    'data': [
        'report/components/report_template_company_info.xml',
        'report/components/report_header_partner_info.xml',
        'report/components/report_main_content.xml',
        'report/components/report_footer.xml',
        'report/home_page/bs_create_form_receipt_th_template.xml',
        'report/home_page/report_bs_create_form_receipt_th_page.xml',
        'report/copy_page/bs_create_form_receipt_th_template_copy.xml',
        'report/copy_page/report_bs_create_form_receipt_th_page_copy.xml',
        'report/request_report.xml',
        'report/set_up_action_report.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}