{
    "name": "BS Create Form Quotation Ramer",
    "version": "17.0.0.3",
    "author": "Basic-Solution Co., Ltd.",
    "maintainer": "varit",
    "website": "https://www.basic-solution.com/",
    "category": "Sales",
    "summary": "Blank quotation report scaffold (header/article/footer) ready for customization",
    "depends": [
        "sale",
        "l10n_th_fonts",
        "l10n_th_partner",
        "partner_contact_person",
        "bs_company_address_ext",
        "bs_sale_order_hrp",
        "bs_multi_discount_sale",
        "bs_sale_order_note_template_modify",
    ],
    "data": [
        "report/components/report_footer.xml",
        "report/components/report_header.xml",
        "report/components/report_main_content.xml",
        "report/report_ramer.xml",
        "report/request_report.xml",
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
