{
    "name": "BS Field Service - Technician Profile",
    "version": "17.0.1.0.1",
    "summary": "Add Technician Profile (PHE / Pump) to Field Service Orders "
    "with profile-specific tabs",
    "author": "Basic Solution Co.,Ltd.",
    "website": "http://www.basic-solution.com",
    "category": "Field Service",
    "depends": [
        "fieldservice",
        "fieldservice_stock",
        "fieldservice_activity",
        "fieldservice_sale",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/bs_equipment_model_views.xml",
        "views/fsm_order_views.xml",
        "views/fsm_team_views.xml",
        "views/fsm_equipment_views.xml",
        "data/ir_sequence_data.xml",
        "data/ir_cron_data.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "bs_fieldservice/static/src/js/phe_line_table.js",
            "bs_fieldservice/static/src/js/pump_line_table.js",
            "bs_fieldservice/static/src/js/equipment_line_table.js",
            "bs_fieldservice/static/src/js/check_sheet_line_list.js",
            "bs_fieldservice/static/src/xml/phe_line_table.xml",
            "bs_fieldservice/static/src/xml/pump_line_table.xml",
            "bs_fieldservice/static/src/xml/equipment_line_table.xml",
            "bs_fieldservice/static/src/xml/check_sheet_line_list.xml",
            "bs_fieldservice/static/src/scss/bs_line_table.scss",
        ],
    },
    "application": False,
    "installable": True,
    "auto_install": False,
    "license": "LGPL-3",
}
