{
    "name": "BS Create Form Quotation Herring Plus Service",
    "version": "17.0.0.4",
    "author": "Basic-Solution Co., Ltd.",
    "maintainer": "varit",
    "website": "https://www.basic-solution.com/",
    "category": "Sales",
    "depends": [
        "sale",
        "salesperson_signature",
        "bs_sale_order_note_template_modify",
        "bs_companies_iso",
        "bs_report_pagination_helper",
        "bs_sale_order_hrp",
    ],
    "data": [
        "report/components/report_footer.xml",
        "report/components/report_header.xml",
        "report/components/report_main_content.xml",
        "report/report_herring_plus_service.xml",
        "report/request_report.xml",
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
